# Generated by Django 5.0.6 on 2026-03-28 17:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AEMesHistorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('nome', models.CharField(max_length=255)),
                ('mes', models.IntegerField()),
                ('ano', models.IntegerField()),
                ('pontuacao', models.IntegerField()),
                ('contribuicoes', models.TextField(blank=True)),
                ('definido_por', models.CharField(max_length=255)),
                ('data_definicao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AllowedEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('user', 'User'), ('viewer', 'Viewer')], default='viewer', max_length=10)),
                ('nome', models.CharField(blank=True, max_length=255)),
                ('avatar_file', models.TextField(blank=True)),
                ('added_by', models.CharField(blank=True, max_length=255)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ferramenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('categoria', models.CharField(choices=[('Modelagem', 'Modelagem'), ('ETL', 'ETL'), ('Visualização', 'Visualização'), ('Utilitários', 'Utilitários')], max_length=50)),
                ('versao', models.CharField(blank=True, max_length=50)),
                ('descricao', models.TextField(blank=True)),
                ('nivel', models.CharField(blank=True, choices=[('Iniciante', 'Iniciante'), ('Intermediário', 'Intermediário'), ('Avançado', 'Avançado')], max_length=20)),
                ('documentacao_link', models.URLField(blank=True)),
                ('autor', models.CharField(max_length=255)),
                ('autor_email', models.EmailField(max_length=254)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=500)),
                ('tipo', models.CharField(choices=[('PDF', 'PDF'), ('Blog Post', 'Blog Post'), ('Website', 'Website'), ('E-book', 'E-book'), ('Tutorial', 'Tutorial'), ('Video', 'Video'), ('Podcast', 'Podcast'), ('Internal Material', 'Internal Material'), ('Other', 'Other')], max_length=50)),
                ('topicos', models.CharField(blank=True, max_length=500)),
                ('descricao', models.TextField()),
                ('url', models.URLField(blank=True)),
                ('autor', models.CharField(max_length=255)),
                ('autor_email', models.EmailField(max_length=254)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RoadmapEntrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=500)),
                ('responsavel', models.CharField(max_length=255)),
                ('prazo', models.CharField(max_length=50)),
                ('prioridade', models.CharField(choices=[('Alta', 'Alta'), ('Média', 'Média'), ('Baixa', 'Baixa')], max_length=10)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('em andamento', 'Em andamento'), ('concluído', 'Concluído')], default='pendente', max_length=20)),
                ('criado_por', models.CharField(max_length=255)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RoadmapFase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fase', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=50)),
                ('data_prevista', models.CharField(max_length=50)),
                ('entregas', models.TextField(blank=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RoadmapProgresso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pilar', models.CharField(max_length=255)),
                ('progresso', models.IntegerField()),
                ('meta', models.CharField(blank=True, max_length=255)),
                ('atualizado_por', models.CharField(max_length=255)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=500)),
                ('descricao', models.TextField(blank=True)),
                ('tema', models.CharField(choices=[('DAX', 'DAX'), ('Tabular Editor', 'Tabular Editor'), ('Python/SQL', 'Python/SQL'), ('Power Automate', 'Power Automate'), ('Performance', 'Performance')], max_length=50)),
                ('nivel', models.CharField(choices=[('Iniciante', 'Iniciante'), ('Intermediário', 'Intermediário'), ('Avançado', 'Avançado')], max_length=20)),
                ('duracao', models.CharField(blank=True, max_length=20)),
                ('youtube_id', models.CharField(blank=True, max_length=20)),
                ('thumbnail_url', models.URLField(blank=True)),
                ('autor', models.CharField(max_length=255)),
                ('autor_email', models.EmailField(max_length=254)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CasoUso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=500)),
                ('contexto', models.CharField(choices=[('Performance', 'Performance'), ('Conectividade', 'Conectividade'), ('UX/UI', 'UX/UI'), ('Governança', 'Governança'), ('Segurança', 'Segurança')], max_length=100)),
                ('tecnologia', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('resultado', models.TextField()),
                ('tags', models.CharField(blank=True, max_length=500)),
                ('autor_email', models.EmailField(max_length=254)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FeedbackCaso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avaliacao', models.IntegerField()),
                ('comentario', models.TextField(blank=True)),
                ('utilidade', models.CharField(choices=[('Muito útil', 'Muito útil'), ('Útil', 'Útil'), ('Pouco útil', 'Pouco útil')], max_length=50)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('caso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='core.casouso')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('caso', 'usuario')},
            },
        ),
    ]
