# Generated by Django 5.0.6 on 2026-03-28 19:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AEMes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, null=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254)),
                ('nome', models.CharField(max_length=255)),
                ('mes', models.IntegerField()),
                ('ano', models.IntegerField()),
                ('pontuacao', models.IntegerField()),
                ('contribuicoes', models.TextField(blank=True)),
                ('definido_por', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['-ano', '-mes'],
                'unique_together': {('mes', 'ano')},
            },
        ),
        migrations.CreateModel(
            name='CasoFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, null=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('avaliacao', models.IntegerField()),
                ('comentario', models.TextField(blank=True)),
                ('utilidade', models.CharField(choices=[('Muito útil', 'Muito útil'), ('Útil', 'Útil'), ('Pouco útil', 'Pouco útil')], max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='AEMesHistorico',
        ),
        migrations.AlterModelOptions(
            name='casouso',
            options={'ordering': ['-data_criacao']},
        ),
        migrations.AlterModelOptions(
            name='ferramenta',
            options={'ordering': ['nome']},
        ),
        migrations.AlterModelOptions(
            name='material',
            options={'ordering': ['-data_criacao']},
        ),
        migrations.AlterModelOptions(
            name='roadmapentrega',
            options={'ordering': ['-data_criacao']},
        ),
        migrations.AlterModelOptions(
            name='roadmapfase',
            options={'ordering': ['data_prevista']},
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['-data_criacao']},
        ),
        migrations.RemoveField(
            model_name='allowedemail',
            name='added_at',
        ),
        migrations.RemoveField(
            model_name='allowedemail',
            name='avatar_file',
        ),
        migrations.RemoveField(
            model_name='casouso',
            name='autor_email',
        ),
        migrations.RemoveField(
            model_name='ferramenta',
            name='autor_email',
        ),
        migrations.RemoveField(
            model_name='material',
            name='autor_email',
        ),
        migrations.RemoveField(
            model_name='roadmapfase',
            name='entregas',
        ),
        migrations.RemoveField(
            model_name='video',
            name='autor_email',
        ),
        migrations.AddField(
            model_name='allowedemail',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
        migrations.AddField(
            model_name='allowedemail',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='allowedemail',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='allowedemail',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ferramenta',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='roadmapentrega',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='roadmapentrega',
            name='fase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entregas', to='core.roadmapfase'),
        ),
        migrations.AddField(
            model_name='roadmapfase',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='roadmapprogresso',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='casouso',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='ferramenta',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='roadmapentrega',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='roadmapentrega',
            name='prazo',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='roadmapentrega',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('em_andamento', 'Em andamento'), ('concluido', 'Concluído')], default='pendente', max_length=20),
        ),
        migrations.AlterField(
            model_name='roadmapfase',
            name='data_prevista',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='roadmapfase',
            name='status',
            field=models.CharField(choices=[('concluido', 'Concluído'), ('andamento', 'Em andamento'), ('planejado', 'Planejado'), ('iniciado', 'Iniciado'), ('agendado', 'Agendado')], max_length=50),
        ),
        migrations.AlterField(
            model_name='video',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='casofeedback',
            name='caso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='core.casouso'),
        ),
        migrations.AddField(
            model_name='casofeedback',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='FeedbackCaso',
        ),
        migrations.AlterUniqueTogether(
            name='casofeedback',
            unique_together={('caso', 'usuario')},
        ),
    ]
