# Generated by Django 5.0.6 on 2026-03-29 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_aemes_casofeedback_delete_aemeshistorico_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Snippet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=500)),
                ('linguagem', models.CharField(max_length=50)),
                ('codigo', models.TextField()),
                ('descricao', models.TextField(blank=True)),
                ('tags', models.CharField(blank=True, max_length=500)),
                ('autor', models.CharField(max_length=255)),
                ('autor_email', models.EmailField(max_length=254)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
