from django.db import migrations


# Sourced from the updated "AE Suggested Certifications List (1).xlsx" spreadsheet,
# which introduces a new classification: Profile & Focus categories, a simplified
# Beginner/Mid-Level/Senior level scale, and a Recommendation field without
# "Must Have" (Recommended / Complementary / Foundations only).

CERTIFICATIONS = [{'titulo': 'Airbyte  API Fundamentals',
  'fornecedor': 'Airbyte',
  'categoria': 'Data Pipelines & Engineering',
  'nivel': 'Mid-Level',
  'prioridade': 'complementary',
  'tipo_certificacao': 'free_course',
  'descricao': 'Teaches how to programmatically manage Airbyte workspaces, connections, jobs, and '
               'triggers using the Airbyte REST API and Terraform provider.',
  'tags': 'airbyte, api, automation, orchestration, data-pipelines, terraform',
  'link_oficial': 'https://airbyteacademy.thinkific.com/courses/api-fundamentals',
  'link_curso': 'https://airbyteacademy.thinkific.com/courses/api-fundamentals'},
 {'titulo': 'Airbyte Build AI Apps',
  'fornecedor': 'Airbyte',
  'categoria': 'Gen AI Solutions',
  'nivel': 'Mid-Level',
  'prioridade': 'complementary',
  'tipo_certificacao': 'free_course',
  'descricao': 'Focuses on integrating raw data sources with vector databases using Airbyte to '
               'build automated RAG pipelines and powered AI chatbots.',
  'tags': 'airbyte, ai, rag, vector-database, chatbot, llm, data-pipelines',
  'link_oficial': 'https://airbyteacademy.thinkific.com/courses/ai-chatbot',
  'link_curso': 'https://airbyteacademy.thinkific.com/courses/ai-chatbot'},
 {'titulo': 'AWS Certified Data Engineer - Associate',
  'fornecedor': 'AWS',
  'categoria': 'Data Pipelines & Engineering',
  'nivel': 'Mid-Level',
  'prioridade': 'complementary',
  'tipo_certificacao': 'paid_exam',
  'descricao': 'Covers core AWS data services including Glue, Redshift, Kinesis, Lake Formation, '
               'and ETL best practices for data engineering.',
  'tags': 'aws, data-engineering, redshift, glue, etl, lake-formation',
  'link_oficial': 'https://aws.amazon.com/certification/certified-data-engineer-associate/',
  'link_curso': 'https://explore.skillbuilder.aws/learn/learning_plan/1858/data-engineer-learning-plan'},
 {'titulo': 'AWS Certified Machine Learning - Specialty',
  'fornecedor': 'AWS',
  'categoria': 'Machine Learning & Advanced Analytics',
  'nivel': 'Senior',
  'prioridade': 'complementary',
  'tipo_certificacao': 'paid_exam',
  'descricao': 'Validates expertise in designing, implementing, deploying, and maintaining ML '
               'solutions on AWS using Amazon SageMaker.',
  'tags': 'aws, machine-learning, sagemaker, ai',
  'link_oficial': 'https://aws.amazon.com/certification/certified-machine-learning-specialty/',
  'link_curso': 'https://explore.skillbuilder.aws/learn/learning_plan/83/machine-learning-learning-plan'},
 {'titulo': 'CDP Data Analyst Exam (CDP-4001)',
  'fornecedor': 'Cloudera',
  'categoria': 'Data Pipelines & Engineering',
  'nivel': 'Senior',
  'prioridade': 'complementary',
  'tipo_certificacao': 'paid_exam',
  'descricao': 'Validates ability to analyze large-scale datasets using Hive, Impala, and Cloudera '
               'Data Platform (CDP) analytical engines.',
  'tags': 'cloudera, cdp, hive, impala, big-data, sql',
  'link_oficial': 'https://www.cloudera.com/about/training/certification.html',
  'link_curso': 'https://www.cloudera.com/about/training/courses.html'},
 {'titulo': 'Confluent Certified Developer for Apache Kafka',
  'fornecedor': 'Confluent',
  'categoria': 'Data Pipelines & Engineering',
  'nivel': 'Senior',
  'prioridade': 'complementary',
  'tipo_certificacao': 'paid_exam',
  'descricao': 'Validates technical skill in developing event-driven streaming applications with '
               'Apache Kafka and Confluent Platform.',
  'tags': 'kafka, confluent, streaming, event-driven, real-time',
  'link_oficial': 'https://www.confluent.io/certification/',
  'link_curso': 'https://developer.confluent.io/learn/kafka-foundations/'},
 {'titulo': 'Databricks Certified Data Engineer Professional',
  'fornecedor': 'Databricks',
  'categoria': 'Data Pipelines & Engineering',
  'nivel': 'Senior',
  'prioridade': 'complementary',
  'tipo_certificacao': 'paid_exam',
  'descricao': 'Advanced exam testing complex ETL pipelines, Delta Live Tables, Auto Loader, '
               'performance tuning, and CI/CD on Databricks.',
  'tags': 'databricks, spark, delta-live-tables, data-engineering, cicd',
  'link_oficial': 'https://www.databricks.com/learn/certification/data-engineer-professional',
  'link_curso': 'https://partner-academy.databricks.com/learn/learning_plan/view/44/data-engineer-learning-plan'},
 {'titulo': 'Databricks GenAI Engineer Associate',
  'fornecedor': 'Databricks',
  'categoria': 'Gen AI Solutions',
  'nivel': 'Mid-Level',
  'prioridade': 'complementary',
  'tipo_certificacao': 'paid_exam',
  'descricao': 'Focuses on developing GenAI applications, vector databases, RAG systems, and LLM '
               'evaluation on Databricks.',
  'tags': 'genai, databricks, rag, vector-search, llm',
  'link_oficial': 'https://www.databricks.com/learn/certification/genai-engineer-associate',
  'link_curso': 'https://partner-academy.databricks.com/learn/learning_plan/view/108/generative-ai-engineer-learning-plan'},
 {'titulo': 'dbt Architect Certification',
  'fornecedor': 'dbt',
  'categoria': 'Cloud Architecture',
  'nivel': 'Senior',
  'prioridade': 'complementary',
  'tipo_certificacao': 'paid_exam',
  'descricao': 'Advanced certification covering multi-project dbt Mesh architectures, governance, '
               'semantic layer design, and enterprise deployment.',
  'tags': 'dbt, dbt-mesh, architecture, semantic-layer',
  'link_oficial': 'https://www.getdbt.com/certifications/dbt-architect',
  'link_curso': 'https://courses.getdbt.com/courses/dbt-certified-architect-path'},
 {'titulo': 'Google Cloud Professional Data Engineer',
  'fornecedor': 'Google',
  'categoria': 'Data Pipelines & Engineering',
  'nivel': 'Senior',
  'prioridade': 'complementary',
  'tipo_certificacao': 'paid_exam',
  'descricao': 'Validates expert ability to design, build, operationalize, and secure data '
               'processing systems on GCP using BigQuery, Dataflow, and Pub/Sub.',
  'tags': 'data-engineering, gcp, bigquery, dataflow, streaming',
  'link_oficial': 'https://cloud.google.com/learn/certification/data-engineer',
  'link_curso': 'https://www.cloudskillsboost.google/paths/16'},
 {'titulo': 'Google Professional ML Engineer',
  'fornecedor': 'Google',
  'categoria': 'Machine Learning & Advanced Analytics',
  'nivel': 'Senior',
  'prioridade': 'complementary',
  'tipo_certificacao': 'paid_exam',
  'descricao': 'Covers building, deploying, monitoring, and scaling machine learning models using '
               'Vertex AI and Google Cloud infrastructure.',
  'tags': 'machine-learning, vertex-ai, mlops, gcp',
  'link_oficial': 'https://cloud.google.com/learn/certification/machine-learning-engineer',
  'link_curso': 'https://www.cloudskillsboost.google/paths/17'},
 {'titulo': 'HashiCorp Certified: Terraform Associate',
  'fornecedor': 'HashiCorp',
  'categoria': 'DevOps',
  'nivel': 'Mid-Level',
  'prioridade': 'complementary',
  'tipo_certificacao': 'paid_exam',
  'descricao': 'Covers Infrastructure as Code concepts with Terraform: state management, modules, '
               'providers, and workspaces. A strong differentiator for AEs.',
  'tags': 'terraform, iac, devops, infrastructure, hashicorp',
  'link_oficial': 'https://www.hashicorp.com/certification/terraform-associate',
  'link_curso': 'https://developer.hashicorp.com/terraform/tutorials/certification'},
 {'titulo': 'CAP — Certified Analytics Professional',
  'fornecedor': 'INFORMS',
  'categoria': 'Machine Learning & Advanced Analytics',
  'nivel': 'Mid-Level',
  'prioridade': 'complementary',
  'tipo_certificacao': 'paid_exam',
  'descricao': 'Professional certification validating end-to-end analytics lifecycle skills from '
               'business framing to model deployment.',
  'tags': 'cap, analytics, analytics-lifecycle, decision-science',
  'link_oficial': 'https://www.certifiedanalytics.org/',
  'link_curso': 'https://www.certifiedanalytics.org/preparing-exam'},
 {'titulo': 'Microsoft Certified: Azure Solutions Architect Expert',
  'fornecedor': 'Microsoft',
  'categoria': 'Cloud Architecture',
  'nivel': 'Senior',
  'prioridade': 'complementary',
  'tipo_certificacao': 'paid_exam',
  'descricao': 'Demonstrates advanced expertise in designing cloud and hybrid solutions running on '
               'Azure, spanning infrastructure, security, and data.',
  'tags': 'architecture, azure, cloud-design, enterprise',
  'link_oficial': 'https://learn.microsoft.com/en-us/credentials/certifications/azure-solutions-architect/',
  'link_curso': 'https://learn.microsoft.com/en-us/training/paths/architect-great-solutions-in-azure/'},
 {'titulo': 'Microsoft Certified: DP-700 (Fabric Data Engineer)',
  'fornecedor': 'Microsoft',
  'categoria': 'Data Pipelines & Engineering',
  'nivel': 'Mid-Level',
  'prioridade': 'complementary',
  'tipo_certificacao': 'paid_exam',
  'descricao': 'Focuses on data ingestion, pipeline orchestration, Spark transformation, and data '
               'lakehouse administration within Microsoft Fabric.',
  'tags': 'fabric, data-engineering, spark, pipelines, onelake',
  'link_oficial': 'https://learn.microsoft.com/en-us/credentials/certifications/fabric-data-engineer-associate/',
  'link_curso': 'https://learn.microsoft.com/en-us/training/paths/ingest-data-fabric/'},
 {'titulo': 'Microsoft Certified: DP-750 (Azure Databricks Data Engineer Associate)',
  'fornecedor': 'Microsoft',
  'categoria': 'Data Pipelines & Engineering',
  'nivel': 'Mid-Level',
  'prioridade': 'complementary',
  'tipo_certificacao': 'paid_exam',
  'descricao': 'Validates expertise in building and deploying optimized pipelines, managing Unity '
               'Catalog governance, and processing data specifically on Azure Databricks.',
  'tags': 'azure, databricks, data-engineering, unity-catalog, delta-lake',
  'link_oficial': 'https://learn.microsoft.com/en-us/credentials/certifications/implementing-data-engineering-solutions-using-azure-databricks/',
  'link_curso': 'https://learn.microsoft.com/en-us/training/paths/prepare-process-data-azure-databricks/'},
 {'titulo': 'Microsoft Certified: AI 102 (Azure AI Engineer Associate)',
  'fornecedor': 'Microsoft',
  'categoria': 'Gen AI Solutions',
  'nivel': 'Mid-Level',
  'prioridade': 'complementary',
  'tipo_certificacao': 'paid_exam',
  'descricao': 'Validates expertise in designing, developing, and deploying Azure AI solutions, '
               'including Azure OpenAI, Cognitive Services, NLP, and agentic workflows.',
  'tags': 'azure, ai-engineer, openai, nlp, computer-vision, ai-solutions',
  'link_oficial': 'https://learn.microsoft.com/en-us/credentials/certifications/azure-ai-engineer/',
  'link_curso': 'https://learn.microsoft.com/en-us/training/paths/get-started-with-artificial-intelligence-on-azure/'},
 {'titulo': 'Microsoft Certified: DP-100  (Azure Data Scientist Associate)',
  'fornecedor': 'Microsoft',
  'categoria': 'Machine Learning & Advanced Analytics',
  'nivel': 'Mid-Level',
  'prioridade': 'complementary',
  'tipo_certificacao': 'paid_exam',
  'descricao': 'Validates expertise in applying data science and machine learning to train, '
               'evaluate, and deploy ML models on Azure using Azure Machine Learning and MLflow.',
  'tags': 'azure, data-science, machine-learning, azure-ml, mlflow, python',
  'link_oficial': 'https://learn.microsoft.com/en-us/credentials/certifications/azure-data-scientist/',
  'link_curso': 'https://learn.microsoft.com/en-us/training/paths/build-1st-machine-learning-model-azure-ml-studio/'},
 {'titulo': 'Salesforce Data Cloud Consultant',
  'fornecedor': 'Salesforce',
  'categoria': 'Cloud Architecture',
  'nivel': 'Senior',
  'prioridade': 'complementary',
  'tipo_certificacao': 'paid_exam',
  'descricao': 'Validates expertise in configuring Salesforce Data Cloud, ingestion streams, '
               'unified customer profiles, data modeling, and Agentforce.',
  'tags': 'salesforce, data-cloud, cdp, agentforce',
  'link_oficial': 'https://trailhead.salesforce.com/credentials/datacloudconsultant',
  'link_curso': 'https://trailhead.salesforce.com/en/credentials/datacloudconsultant'},
 {'titulo': 'SnowPro Advanced: Architect',
  'fornecedor': 'Snowflake',
  'categoria': 'Cloud Architecture',
  'nivel': 'Senior',
  'prioridade': 'complementary',
  'tipo_certificacao': 'paid_exam',
  'descricao': 'Advanced exam testing end-to-end multi-cloud architecture, account replication, '
               'security controls, and data sharing in Snowflake.',
  'tags': 'snowflake, architecture, security, data-sharing',
  'link_oficial': 'https://www.snowflake.com/en/learn/certification/snowpro-advanced-architect/',
  'link_curso': 'https://learn.snowflake.com/en/courses/snowpro-advanced-architect-prep/'},
 {'titulo': 'SnowPro Advanced: Data Engineer',
  'fornecedor': 'Snowflake',
  'categoria': 'Data Pipelines & Engineering',
  'nivel': 'Senior',
  'prioridade': 'complementary',
  'tipo_certificacao': 'paid_exam',
  'descricao': 'Tests advanced data engineering practices on Snowflake, including Snowpark, '
               'Streams, Tasks, Python UDFs, and pipeline orchestration.',
  'tags': 'snowflake, snowpark, python, streams-tasks',
  'link_oficial': 'https://www.snowflake.com/en/learn/certification/snowpro-advanced-data-engineer/',
  'link_curso': 'https://learn.snowflake.com/en/courses/snowpro-advanced-data-engineer-prep/'},
 {'titulo': 'Applied AI Foundations',
  'fornecedor': 'OpenAI',
  'categoria': 'Gen AI Solutions',
  'nivel': 'Mid-Level',
  'prioridade': 'complementary',
  'tipo_certificacao': 'free_course',
  'descricao': 'Focuses on turning recurring tasks into repeatable AI workflows, breaking work '
               'into steps, identifying ChatGPT integration points, and building review controls.',
  'tags': 'openai, chatgpt, workflows, prompting, ai-automation',
  'link_oficial': 'https://academy.openai.com/public/courses/applied-ai-foundations-hgk7r',
  'link_curso': 'https://academy.openai.com/public/courses/applied-ai-foundations-hgk7r'},
 {'titulo': 'Agents and Workflows',
  'fornecedor': 'OpenAI',
  'categoria': 'Gen AI Solutions',
  'nivel': 'Mid-Level',
  'prioridade': 'complementary',
  'tipo_certificacao': 'free_course',
  'descricao': 'Teaches how to direct AI agents through structured work, set boundaries, define '
               'outputs, review drafts, and build reusable multi-step agentic workflows.',
  'tags': 'openai, agents, workflows, agentic-ai, chatgpt, llm',
  'link_oficial': 'https://academy.openai.com/public/courses/agents-and-workflows-bieml',
  'link_curso': 'https://academy.openai.com/public/courses/agents-and-workflows-bieml'},
 {'titulo': 'Claude Certified Developer – Foundations',
  'fornecedor': 'Anthropic',
  'categoria': 'Gen AI Solutions',
  'nivel': 'Mid-Level',
  'prioridade': 'complementary',
  'tipo_certificacao': 'paid_exam',
  'descricao': 'Validates technical skills in building applications using Claude APIs, SDKs, '
               'function calling, tool use, and structured outputs.',
  'tags': 'anthropic, claude, api, python, tool-use, function-calling, ai-engineering',
  'link_oficial': 'https://anthropic-partners.skilljar.com/claude-certified-developer-foundations-certification',
  'link_curso': 'https://anthropic-partners.skilljar.com/claude-certified-developer-foundations-certification'},
 {'titulo': 'Claude Certified Architect – Professional',
  'fornecedor': 'Anthropic',
  'categoria': 'Gen AI Solutions',
  'nivel': 'Senior',
  'prioridade': 'complementary',
  'tipo_certificacao': 'paid_exam',
  'descricao': 'Advanced certification validating complex multi-agent orchestration, Model Context '
               'Protocol (MCP) servers, enterprise scale, and security.',
  'tags': 'anthropic, claude, mcp, multi-agent, enterprise-architecture, ai-orchestration',
  'link_oficial': 'https://anthropic-partners.skilljar.com/claude-certified-architect-professional-certification',
  'link_curso': 'https://anthropic-partners.skilljar.com/claude-certified-architect-professional-certification'},
 {'titulo': 'Airbyte Cloud Fundamentals',
  'fornecedor': 'Airbyte',
  'categoria': 'Data Pipelines & Engineering',
  'nivel': 'Beginner',
  'prioridade': 'foundations',
  'tipo_certificacao': 'free_course',
  'descricao': 'Covers data replication pipelines using Airbyte Cloud, marketplace connector '
               'configuration, sync modes, and loading to cloud warehouses.',
  'tags': 'airbyte, elt, ingestion, open-source, connectors, cloud',
  'link_oficial': 'https://airbyteacademy.thinkific.com/products/courses/101-cloud-fundamentals',
  'link_curso': 'https://airbyteacademy.thinkific.com/products/courses/101-cloud-fundamentals'},
 {'titulo': 'Apache Airflow Fundamentals',
  'fornecedor': 'Astronomer',
  'categoria': 'Data Pipelines & Engineering',
  'nivel': 'Beginner',
  'prioridade': 'foundations',
  'tipo_certificacao': 'paid_exam',
  'descricao': 'Validates core understanding of Apache Airflow architecture, components '
               '(Scheduler, Executor, Webserver), and fundamental pipeline orchestration concepts.',
  'tags': 'airflow, orchestration, astronomer, dags, python, foundations',
  'link_oficial': 'https://academy.astronomer.io/certification-exam-apache-airflow-3-fundamentals',
  'link_curso': 'https://academy.astronomer.io/path/airflow-101'},
 {'titulo': 'AWS Certified Cloud Practitioner (CLF-C02)',
  'fornecedor': 'AWS',
  'categoria': 'Cloud Architecture',
  'nivel': 'Beginner',
  'prioridade': 'foundations',
  'tipo_certificacao': 'paid_exam',
  'descricao': 'Provides an overall understanding of AWS Cloud platform fundamentals, security, '
               'compliance, core services, and cloud billing.',
  'tags': 'aws, cloud-practitioner, cloud-basics, s3',
  'link_oficial': 'https://aws.amazon.com/certification/certified-cloud-practitioner/',
  'link_curso': 'https://explore.skillbuilder.aws/learn/learning_plan/133/cloud-essentials-learning-plan'},
 {'titulo': 'CompTIA Data+',
  'fornecedor': 'CompTIA',
  'categoria': 'Analytics Engineering Roadmap',
  'nivel': 'Beginner',
  'prioridade': 'foundations',
  'tipo_certificacao': 'paid_exam',
  'descricao': 'Certification validating data mining, data analysis, visualization, governance, '
               'and reporting concepts.',
  'tags': 'comptia, data-plus, data-literacy',
  'link_oficial': 'https://www.comptia.org/certifications/data',
  'link_curso': 'https://www.comptia.org/training/by-certification/data'},
 {'titulo': 'Databricks Fundamentals',
  'fornecedor': 'Databricks',
  'categoria': 'Data Pipelines & Engineering',
  'nivel': 'Beginner',
  'prioridade': 'foundations',
  'tipo_certificacao': 'free_course',
  'descricao': 'Covers core Lakehouse concepts, Delta Lake architecture, Databricks SQL, and '
               'unified data analytics principles.',
  'tags': 'databricks, lakehouse, delta-lake, core, foundations',
  'link_oficial': 'https://partner-academy.databricks.com/learn/courses/2308/databricks-fundamentals-accreditation',
  'link_curso': 'https://partner-academy.databricks.com/learn/courses/2206/databricks-fundamentals'},
 {'titulo': 'Databricks Generative AI Fundamentals',
  'fornecedor': 'Databricks',
  'categoria': 'Gen AI Solutions',
  'nivel': 'Beginner',
  'prioridade': 'foundations',
  'tipo_certificacao': 'free_course',
  'descricao': 'Introduces foundational Generative AI concepts, LLMs, fine-tuning vs RAG, and '
               'business applications on Databricks.',
  'tags': 'databricks, genai, llm, ai-fundamentals, foundations',
  'link_oficial': 'https://partner-academy.databricks.com/learn/courses/1811/generative-ai-fundamentals-accreditation',
  'link_curso': 'https://partner-academy.databricks.com/learn/courses/1765/generative-ai-fundamentals'},
 {'titulo': 'dbt Fundamentals',
  'fornecedor': 'dbt',
  'categoria': 'Data Pipelines & Engineering',
  'nivel': 'Beginner',
  'prioridade': 'foundations',
  'tipo_certificacao': 'free_course',
  'descricao': 'Free course teaching dbt Core basics: models, sources, refs, materializations, '
               'testing, and documentation.',
  'tags': 'dbt, dbt-core, sql, transformations',
  'link_oficial': 'https://courses.getdbt.com/courses/fundamentals',
  'link_curso': 'https://courses.getdbt.com/courses/fundamentals'},
 {'titulo': 'Google Data Analytics Professional Certificate',
  'fornecedor': 'Google',
  'categoria': 'BI Tooling & DataViz',
  'nivel': 'Beginner',
  'prioridade': 'foundations',
  'tipo_certificacao': 'free_course',
  'descricao': 'Teaches fundamental data analysis skills including SQL, R, Tableau, and data '
               'cleaning for entry-level data roles.',
  'tags': 'data-analytics, sql, tableau, r, spreadsheet',
  'link_oficial': 'https://www.coursera.org/professional-certificates/google-data-analytics',
  'link_curso': 'https://www.coursera.org/professional-certificates/google-data-analytics'},
 {'titulo': 'Google Cloud Digital Leader',
  'fornecedor': 'Google',
  'categoria': 'Cloud Architecture',
  'nivel': 'Beginner',
  'prioridade': 'foundations',
  'tipo_certificacao': 'paid_exam',
  'descricao': 'Validates core knowledge of Google Cloud products, services, security, and digital '
               'transformation strategy.',
  'tags': 'gcp, cloud-fundamentals, gcp-digital-leader, strategy',
  'link_oficial': 'https://cloud.google.com/learn/certification/cloud-digital-leader',
  'link_curso': 'https://www.cloudskillsboost.google/paths/9'},
 {'titulo': 'Google Generative AI Leader',
  'fornecedor': 'Google',
  'categoria': 'Gen AI Solutions',
  'nivel': 'Beginner',
  'prioridade': 'foundations',
  'tipo_certificacao': 'paid_exam',
  'descricao': 'Validates foundational literacy in Generative AI concepts, business use cases, '
               'responsible AI principles, and GCP GenAI capabilities.',
  'tags': 'gcp, generative-ai, ai-fundamentals, leader, responsible-ai',
  'link_oficial': 'https://cloud.google.com/learn/certification/generative-ai-leader',
  'link_curso': 'https://www.cloudskillsboost.google/paths/118'},
 {'titulo': 'Google UX Design Professional',
  'fornecedor': 'Google',
  'categoria': 'UI/UX Designer',
  'nivel': 'Beginner',
  'prioridade': 'foundations',
  'tipo_certificacao': 'free_course',
  'descricao': 'Covers UX research, wireframing, prototyping in Figma, and usability testing. '
               'Complementary for AEs designing end-user data products.',
  'tags': 'ux-ui, figma, prototyping, user-research, dashboard-design',
  'link_oficial': 'https://www.coursera.org/professional-certificates/google-ux-design',
  'link_curso': 'https://www.coursera.org/professional-certificates/google-ux-design'},
 {'titulo': 'IBM Data Analyst Professional Certificate',
  'fornecedor': 'IBM',
  'categoria': 'BI Tooling & DataViz',
  'nivel': 'Beginner',
  'prioridade': 'foundations',
  'tipo_certificacao': 'free_course',
  'descricao': 'Professional certificate covering data analysis basics, Python, SQL, data '
               'visualization, IBM Cognos, and Excel.',
  'tags': 'ibm, data-analysis, python, sql, excel, cognos',
  'link_oficial': 'https://www.coursera.org/professional-certificates/ibm-data-analyst',
  'link_curso': 'https://www.coursera.org/professional-certificates/ibm-data-analyst'},
 {'titulo': 'Meta Data Analyst Professional Certificate',
  'fornecedor': 'Meta',
  'categoria': 'BI Tooling & DataViz',
  'nivel': 'Beginner',
  'prioridade': 'foundations',
  'tipo_certificacao': 'free_course',
  'descricao': 'Covers foundational data analysis, SQL, Tableau, statistical analysis, and '
               'business intelligence techniques for data roles.',
  'tags': 'meta, data-analyst, sql, tableau, statistics, bi',
  'link_oficial': 'https://www.coursera.org/professional-certificates/meta-data-analyst',
  'link_curso': 'https://www.coursera.org/professional-certificates/meta-data-analyst'},
 {'titulo': 'Microsoft Certified: PL-900 (Power Platform Fundamentals)',
  'fornecedor': 'Microsoft',
  'categoria': 'BI Tooling & DataViz',
  'nivel': 'Beginner',
  'prioridade': 'foundations',
  'tipo_certificacao': 'paid_exam',
  'descricao': 'Covers business value and basic capabilities of Power Platform tools, including '
               'Power BI, Power Apps, and Power Automate.',
  'tags': 'power-platform, power-bi, low-code, automation',
  'link_oficial': 'https://learn.microsoft.com/en-us/credentials/certifications/power-platform-fundamentals/',
  'link_curso': 'https://learn.microsoft.com/en-us/training/paths/power-plat-fundamentals/'},
 {'titulo': 'Microsoft Certified: AZ-900 (Azure Fundamentals)',
  'fornecedor': 'Microsoft',
  'categoria': 'Cloud Architecture',
  'nivel': 'Beginner',
  'prioridade': 'foundations',
  'tipo_certificacao': 'paid_exam',
  'descricao': 'Validates foundational knowledge of cloud concepts, Azure architecture, services, '
               'governance, and management tools.',
  'tags': 'cloud, azure, foundations, infrastructure',
  'link_oficial': 'https://learn.microsoft.com/en-us/credentials/certifications/azure-fundamentals/',
  'link_curso': 'https://learn.microsoft.com/en-us/training/paths/microsoft-azure-fundamentals-describe-cloud-concepts/'},
 {'titulo': 'Microsoft Certified: DP-900 (Azure Data Fundamentals)',
  'fornecedor': 'Microsoft',
  'categoria': 'Data Pipelines & Engineering',
  'nivel': 'Beginner',
  'prioridade': 'foundations',
  'tipo_certificacao': 'paid_exam',
  'descricao': 'Covers foundational core data concepts and Azure data services across relational, '
               'non-relational, and analytical workloads.',
  'tags': 'data-fundamentals, azure, sql, analytics',
  'link_oficial': 'https://learn.microsoft.com/en-us/credentials/certifications/azure-data-fundamentals/',
  'link_curso': 'https://learn.microsoft.com/en-us/training/paths/azure-data-fundamentals-explore-core-data-concepts/'},
 {'titulo': 'Microsoft Certified: AI-900 (Azure AI Fundamentals)',
  'fornecedor': 'Microsoft',
  'categoria': 'Gen AI Solutions',
  'nivel': 'Beginner',
  'prioridade': 'foundations',
  'tipo_certificacao': 'paid_exam',
  'descricao': 'Demonstrates knowledge of common AI and Machine Learning workloads, ethical AI '
               'principles, and Azure AI services.',
  'tags': 'ai-fundamentals, machine-learning, azure, nlp',
  'link_oficial': 'https://learn.microsoft.com/en-us/credentials/certifications/azure-ai-fundamentals/',
  'link_curso': 'https://learn.microsoft.com/en-us/training/paths/get-started-with-artificial-intelligence-on-azure/'},
 {'titulo': 'Tableau Desktop Foundations',
  'fornecedor': 'Salesforce',
  'categoria': 'BI Tooling & DataViz',
  'nivel': 'Beginner',
  'prioridade': 'foundations',
  'tipo_certificacao': 'free_course',
  'descricao': 'Entry-level Tableau certification covering core product knowledge: connecting to '
               'data, building basic visualizations, and navigating the interface.',
  'tags': 'tableau, dataviz, bi, charts, desktop-foundations',
  'link_oficial': 'https://www.tableau.com/learn/certification/desktop-specialist',
  'link_curso': 'https://trailhead.salesforce.com/en/credentials/tableau-desktop-specialist'},
 {'titulo': 'SnowPro Core Certification',
  'fornecedor': 'Snowflake',
  'categoria': 'Data Pipelines & Engineering',
  'nivel': 'Beginner',
  'prioridade': 'foundations',
  'tipo_certificacao': 'paid_exam',
  'descricao': "Validates expertise in Snowflake's cloud data platform: warehouse architecture, "
               'performance tuning, security, virtual warehouses, and advanced SQL.',
  'tags': 'snowflake, snowpro, cloud-data-warehouse, sql',
  'link_oficial': 'https://www.snowflake.com/en/learn/certification/snowpro-core/',
  'link_curso': 'https://learn.snowflake.com/en/courses/snowpro-core-prep/'},
 {'titulo': 'AI Foundations',
  'fornecedor': 'OpenAI',
  'categoria': 'Gen AI Solutions',
  'nivel': 'Beginner',
  'prioridade': 'foundations',
  'tipo_certificacao': 'free_course',
  'descricao': 'Teaches the basics of AI, large language models, and ChatGPT, focusing on clear '
               'prompting, context management, and responsible AI use in everyday work.',
  'tags': 'openai, chatgpt, ai-foundations, llm, prompting',
  'link_oficial': 'https://academy.openai.com/public/courses/ai-foundations-juzjs',
  'link_curso': 'https://academy.openai.com/public/courses/ai-foundations-juzjs'},
 {'titulo': 'Claude Certified Associate – Foundations',
  'fornecedor': 'Anthropic',
  'categoria': 'Gen AI Solutions',
  'nivel': 'Beginner',
  'prioridade': 'foundations',
  'tipo_certificacao': 'paid_exam',
  'descricao': 'Validates core knowledge of Claude platform capabilities, prompt design '
               'principles, AI safety, and everyday enterprise use cases.',
  'tags': 'anthropic, claude, prompt-engineering, llm, foundations',
  'link_oficial': 'https://anthropic-partners.skilljar.com/claude-certified-associate-foundations-certification',
  'link_curso': 'https://anthropic-partners.skilljar.com/claude-certified-associate-foundations-certification'},
 {'titulo': 'PyAirbyte Fundamentals',
  'fornecedor': 'Airbyte',
  'categoria': 'Data Pipelines & Engineering',
  'nivel': 'Mid-Level',
  'prioridade': 'recommended',
  'tipo_certificacao': 'free_course',
  'descricao': 'Teaches how to use PyAirbyte to manage programmatic data pipelines in Python, '
               'build custom connectors, and feed vector databases for AI/RAG.',
  'tags': 'airbyte, pyairbyte, python, data-pipelines, elt, ai-integration',
  'link_oficial': 'https://airbyteacademy.thinkific.com/courses/pyairbyte-fundamentals',
  'link_curso': 'https://airbyteacademy.thinkific.com/courses/pyairbyte-fundamentals'},
 {'titulo': 'Apache Airflow DAG Authoring',
  'fornecedor': 'Astronomer',
  'categoria': 'Data Pipelines & Engineering',
  'nivel': 'Mid-Level',
  'prioridade': 'recommended',
  'tipo_certificacao': 'paid_exam',
  'descricao': 'Validates expertise in writing Python DAGs, TaskFlow API, XComs, dynamic DAG '
               'generation, branching, sensors, and pipeline authoring best practices.',
  'tags': 'airflow, dags, python, taskflow-api, orchestration, astronomer',
  'link_oficial': 'https://academy.astronomer.io/astronomer-certification-apache-airflow-dag-authoring',
  'link_curso': 'https://academy.astronomer.io/astronomer-certification-apache-airflow-dag-authoring-preparation'},
 {'titulo': 'Databricks Certified Data Analyst Associate',
  'fornecedor': 'Databricks',
  'categoria': 'BI Tooling & DataViz',
  'nivel': 'Mid-Level',
  'prioridade': 'recommended',
  'tipo_certificacao': 'paid_exam',
  'descricao': 'Must-have certification validating ability to use Databricks SQL and dashboards '
               'for data analysis and visualization on the Lakehouse.',
  'tags': 'databricks, sql, data-analyst, lakehouse, dashboards, must-have',
  'link_oficial': 'https://www.databricks.com/learn/certification/data-analyst-associate',
  'link_curso': 'https://partner-academy.databricks.com/learn/learning_plan/view/42/data-analyst-learning-plan'},
 {'titulo': 'Databricks Certified Data Engineer Associate',
  'fornecedor': 'Databricks',
  'categoria': 'Data Pipelines & Engineering',
  'nivel': 'Mid-Level',
  'prioridade': 'recommended',
  'tipo_certificacao': 'paid_exam',
  'descricao': 'Validates basic ETL task execution, Spark SQL, Delta Lake operations, and pipeline '
               'building using Databricks.',
  'tags': 'databricks, spark, delta-lake, etl, data-engineering',
  'link_oficial': 'https://www.databricks.com/learn/certification/data-engineer-associate',
  'link_curso': 'https://partner-academy.databricks.com/learn/learning_plan/view/43/data-engineer-associate-learning-plan'},
 {'titulo': 'dbt Certified Developer (dbt Analytics Engineering Certification)',
  'fornecedor': 'dbt',
  'categoria': 'Analytics Engineering Roadmap',
  'nivel': 'Mid-Level',
  'prioridade': 'recommended',
  'tipo_certificacao': 'paid_exam',
  'descricao': 'Industry gold standard for Analytics Engineers. Validates modular SQL, dbt '
               'Cloud/Core development, testing, Jinja, and CI/CD.',
  'tags': 'dbt, analytics-engineering, jinja, testing, elt',
  'link_oficial': 'https://www.getdbt.com/dbt-assets/certifications/dbt-certificate-study-guide',
  'link_curso': 'https://courses.getdbt.com/courses/dbt-certified-developer-path'},
 {'titulo': 'Google Associate Data Practitioner',
  'fornecedor': 'Google',
  'categoria': 'Analytics Engineering Roadmap',
  'nivel': 'Mid-Level',
  'prioridade': 'recommended',
  'tipo_certificacao': 'paid_exam',
  'descricao': 'Validates foundational technical capability in GCP data tools including BigQuery, '
               'Looker, and analytical data pipelines.',
  'tags': 'gcp, bigquery, looker, data-practitioner, sql',
  'link_oficial': 'https://cloud.google.com/learn/certification/data-practitioner',
  'link_curso': 'https://www.cloudskillsboost.google/paths/223'},
 {'titulo': 'Gemini Enterprise Agent Development (Partner Specialist)',
  'fornecedor': 'Google',
  'categoria': 'Gen AI Solutions',
  'nivel': 'Mid-Level',
  'prioridade': 'recommended',
  'tipo_certificacao': 'free_course',
  'descricao': 'Specialized partner certification focused on building, orchestrating, and '
               'deploying Enterprise AI Agents using Gemini and Vertex AI.',
  'tags': 'gemini, agents, agentic-ai, partner-specialist, vertex-ai, llm',
  'link_oficial': 'https://rsvp.withgoogle.com/events/partner-learning/cps',
  'link_curso': 'https://rsvp.withgoogle.com/events/partner-learning/cps'},
 {'titulo': 'Microsoft Certified: DP-600 (Fabric Analytics Engineer)',
  'fornecedor': 'Microsoft',
  'categoria': 'Analytics Engineering Roadmap',
  'nivel': 'Mid-Level',
  'prioridade': 'recommended',
  'tipo_certificacao': 'paid_exam',
  'descricao': 'Focuses on designing, creating, and deploying analytics solutions using Microsoft '
               'Fabric, OneLake, Lakehouses, and semantic models.',
  'tags': 'fabric, analytics-engineering, onelake, sql, dax',
  'link_oficial': 'https://learn.microsoft.com/en-us/credentials/certifications/fabric-analytics-engineer-associate/',
  'link_curso': 'https://learn.microsoft.com/en-us/training/paths/get-started-fabric/'},
 {'titulo': 'Microsoft Certified: PL-300 (Power BI Data Analyst)',
  'fornecedor': 'Microsoft',
  'categoria': 'BI Tooling & DataViz',
  'nivel': 'Mid-Level',
  'prioridade': 'recommended',
  'tipo_certificacao': 'paid_exam',
  'descricao': 'Validates expertise in transforming, modeling, visualizing, and analyzing data '
               'using Power BI, including DAX formulas.',
  'tags': 'power-bi, dax, dataviz, semantic-model, bi',
  'link_oficial': 'https://learn.microsoft.com/en-us/credentials/certifications/data-analyst-associate/',
  'link_curso': 'https://learn.microsoft.com/en-us/training/paths/data-analytics-microsoft/'},
 {'titulo': 'Tableau Certified Data Analyst',
  'fornecedor': 'Salesforce',
  'categoria': 'BI Tooling & DataViz',
  'nivel': 'Mid-Level',
  'prioridade': 'recommended',
  'tipo_certificacao': 'paid_exam',
  'descricao': 'Validates ability to enable data-driven business decisions by connecting to data, '
               'building dashboards, and configuring Tableau Prep.',
  'tags': 'tableau, data-analyst, lod, tableau-prep',
  'link_oficial': 'https://www.tableau.com/learn/certification/data-analyst',
  'link_curso': 'https://trailhead.salesforce.com/en/credentials/tableaudataanayst'},
 {'titulo': 'Claude Certified Architect – Foundations',
  'fornecedor': 'Anthropic',
  'categoria': 'Gen AI Solutions',
  'nivel': 'Mid-Level',
  'prioridade': 'recommended',
  'tipo_certificacao': 'paid_exam',
  'descricao': 'Validates foundational architecture skills for enterprise GenAI systems, RAG '
               'integration, context windows, and safety controls with Claude.',
  'tags': 'anthropic, claude, architecture, rag, enterprise-ai, system-design',
  'link_oficial': 'https://anthropic-partners.skilljar.com/claude-certified-architect-foundations-certification',
  'link_curso': 'https://anthropic-partners.skilljar.com/claude-certified-architect-foundations-certification'}]



def migrate_certifications(apps, schema_editor):
    from django.db import connection
    with connection.cursor() as cursor:
        # Archive the previous catalog instead of deleting it, so that any
        # CertificationProgress rows (FK -> certifications, ON DELETE CASCADE)
        # keep pointing at a valid row and nobody's tracked progress is lost.
        cursor.execute("UPDATE certifications SET ativo = FALSE WHERE ativo = TRUE")

        # Safety net: normalize any certification still using a level/priority
        # value from a previous scale, in case it isn't re-inserted below.
        cursor.execute("UPDATE certifications SET nivel = %s WHERE nivel = %s", ['Mid-Level', 'Intermediate'])
        cursor.execute("UPDATE certifications SET nivel = %s WHERE nivel = %s", ['Senior', 'Advanced'])
        cursor.execute("UPDATE certifications SET nivel = %s WHERE nivel = %s", ['Beginner', 'Junior'])
        cursor.execute("UPDATE certifications SET nivel = %s WHERE nivel = %s", ['Mid-Level', 'Mid-level'])
        cursor.execute("UPDATE certifications SET prioridade = %s WHERE prioridade = %s", ['recommended', 'must_have'])

        for cert in CERTIFICATIONS:
            cursor.execute("""
                INSERT INTO certifications
                    (titulo, fornecedor, categoria, nivel, prioridade, tipo_certificacao,
                     descricao, tags, link_oficial, link_curso, ativo, data_criacao)
                SELECT %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, TRUE, NOW()
                WHERE NOT EXISTS (
                    SELECT 1 FROM certifications WHERE titulo = %s
                )
            """, [
                cert['titulo'], cert['fornecedor'], cert['categoria'],
                cert['nivel'], cert['prioridade'], cert['tipo_certificacao'],
                cert['descricao'], cert['tags'], cert['link_oficial'], cert['link_curso'],
                cert['titulo'],
            ])


def reverse_migrate_certifications(apps, schema_editor):
    from django.db import connection
    with connection.cursor() as cursor:
        # Remove the newly-seeded rows and restore the previously active catalog.
        cursor.execute("DELETE FROM certifications WHERE titulo = ANY(%s)", [
            [c['titulo'] for c in CERTIFICATIONS]
        ])
        cursor.execute("UPDATE certifications SET ativo = TRUE WHERE ativo = FALSE")


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_seed_ae_suggested_certifications'),
    ]

    operations = [
        migrations.RunPython(migrate_certifications, reverse_code=reverse_migrate_certifications),
    ]
